id: P009257
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:30:18.697386
source_metadata:
  id: bdr:W1CZ1992
  title: ཆོས་ཀྱི་རྒྱ་མཚོའི་རྣམ་ཐར་མདོར་བསྡུས་ངོ་མཚར་ཡོངས་འདུས་ལྗོན་བཟང་
  author: ''
  volumes:
    687b5d73292148eb930cb7d48afd73bc:
      image_group_id: I1CZ2027
      title: ''
      volume_number: 1
      total_pages: 238
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
