id: I883AC523
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T00:42:58+00:00'
last_modified: '2022-06-08T09:44:09.543079+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1992
  title: ཆོས་ཀྱི་རྒྱ་མཚོའི་རྣམ་ཐར་མདོར་བསྡུས་ངོ་མཚར་ཡོངས་འདུས་ལྗོན་བཟང་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    45A6:
      image_group_id: I1CZ2027
      title: ''
      total_pages: 238
      order: 1
      base_file: 45A6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
